### ISSUE TITLE
[question] why would the password be trimmed ?  

### ISSUE THREAD

**Issue by scr2em** [bishkou/password-checker#3]
hello, thanks for your great work

why would the password be trimmed   passwords can possibly includes "space" at the end.

**Comment by bishkou** [comment]
Hello, well to be honest I didn't think anyone used spaces on their passwords haha
I can fix if that's the case

**Comment by scr2em** [comment]
Yeah, I do use spaces in my passwords xD 
long story short, my friend tried to use a keylogger, he got one of my passwords but he couldn't use it.
It had a space at the end that he didn't even notice. lol

**Comment by bishkou** [comment]
Hahaha I'll have to start using spaces then
